<?php

namespace Projectx\AccountBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountGroupRepository extends EntityRepository
{
}