<?php

namespace Projectx\AccountBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository {
	
	/**
     * Récupère le compte avec son groupe
	 * @param type $id
	 * @return Account
	 */
	public function findWithGroup($id) {
		try {
			$qb = $this->createQueryBuilder('a');
			$qb->select('a, ag')
				->leftJoin('a.group', 'ag')
				->where('a.id = ' . $id);
			return $qb->getQuery()
					->getOneOrNullResult();
		} catch(\Doctrine\ORM\ORMException $e) {
			return null;
		}
	}
	
	/**
     * Récupère tous les comptes avec leur groupe
	 * @return Account[]
	 */
	public function findAllWithGroup() {
		$qb = $this->createQueryBuilder('a');
		$qb->select('a, ag')
			->leftJoin('a.group', 'ag');
				
		return $qb->getQuery()
				->getResult();
	}
	
}