Home:
    pattern:  /home
    defaults: { _controller: ProjectxAccountBundle:default:index }

SyncAccount:
    pattern: /syncaccount/{id}
    defaults: { _controller: ProjectxAccountBundle:default:syncAccount }
    requirements:
        id: \d*

AddAccount:
    pattern: /addaccount
    defaults: { _controller: ProjectxAccountBundle:default:addAccount }

DeleteAccount:
    pattern: /deleteaccount/{id}
    defaults: { _controller: ProjectxAccountBundle:default:deleteAccount }
    requirements:
        id: \d+

UpdateAccount:
    pattern: /updateaccount/{id}
    defaults: { _controller: ProjectxAccountBundle:default:updateAccount }
    requirements:
        id: \d+
