parameters:
#    projectx_account_management.example.class: Projectx\AccountBundle\Example

services:
#    projectx_account_management.example:
#        class: %projectx_account_management.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
